// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrototypeApp.Services;

namespace PrototypeApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PrototypeApp.Model.BendingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Bmax")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("CostM")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<int>("Energ")
                        .HasColumnType("int");

                    b.Property<string>("G_Name")
                        .HasColumnType("longtext");

                    b.Property<int>("LBH")
                        .HasColumnType("int");

                    b.Property<int>("Lmax")
                        .HasColumnType("int");

                    b.Property<int>("Massa")
                        .HasColumnType("int");

                    b.Property<int>("NGN")
                        .HasColumnType("int");

                    b.Property<int>("NUN")
                        .HasColumnType("int");

                    b.Property<int>("Pkh")
                        .HasColumnType("int");

                    b.Property<int>("Ptc")
                        .HasColumnType("int");

                    b.Property<int>("Sdv")
                        .HasColumnType("int");

                    b.Property<int>("Sod")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .HasColumnType("longtext");

                    b.Property<string>("VI")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BendingMachines");
                });

            modelBuilder.Entity("PrototypeApp.Model.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AppProgram")
                        .HasColumnType("longtext");

                    b.Property<string>("Com_Name")
                        .HasColumnType("longtext");

                    b.Property<int>("CountM")
                        .HasColumnType("int");

                    b.Property<string>("Program")
                        .HasColumnType("longtext");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<int>("Rm")
                        .HasColumnType("int");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.Property<int>("Vprog")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("PrototypeApp.Model.CuttingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Abr")
                        .HasColumnType("int");

                    b.Property<string>("AbrM")
                        .HasColumnType("longtext");

                    b.Property<int>("B")
                        .HasColumnType("int");

                    b.Property<string>("C_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("CostM")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<int>("Energ")
                        .HasColumnType("int");

                    b.Property<int>("L")
                        .HasColumnType("int");

                    b.Property<int>("Massa")
                        .HasColumnType("int");

                    b.Property<int>("NGN")
                        .HasColumnType("int");

                    b.Property<int>("NUN")
                        .HasColumnType("int");

                    b.Property<int>("Pnom")
                        .HasColumnType("int");

                    b.Property<int>("Ppump")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .HasColumnType("longtext");

                    b.Property<string>("VI")
                        .HasColumnType("longtext");

                    b.Property<int>("Vmax")
                        .HasColumnType("int");

                    b.Property<int>("Vs")
                        .HasColumnType("int");

                    b.Property<int>("Vtra")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CuttingMachines");
                });

            modelBuilder.Entity("PrototypeApp.Model.DrillingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("CostM")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("D_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<int>("Dmax")
                        .HasColumnType("int");

                    b.Property<int>("E1")
                        .HasColumnType("int");

                    b.Property<int>("E2")
                        .HasColumnType("int");

                    b.Property<int>("Emax")
                        .HasColumnType("int");

                    b.Property<int>("Energ")
                        .HasColumnType("int");

                    b.Property<string>("LBH")
                        .HasColumnType("longtext");

                    b.Property<double>("Massa")
                        .HasColumnType("double");

                    b.Property<int>("NGN")
                        .HasColumnType("int");

                    b.Property<int>("NUN")
                        .HasColumnType("int");

                    b.Property<int>("SumN")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .HasColumnType("longtext");

                    b.Property<string>("VI")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DrillingMachines");
                });

            modelBuilder.Entity("PrototypeApp.Model.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BendingMachineId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BendingMachinesAmount")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CuttingMachineId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CuttingMachinesAmount")
                        .HasColumnType("int");

                    b.Property<Guid>("DrillingMachineId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DrillingMachinesAmount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("SelectedCompany")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WeldingMachineId")
                        .HasColumnType("char(36)");

                    b.Property<int>("WeldingMachinesAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("PrototypeApp.Model.Settings", b =>
                {
                    b.Property<double>("Ks")
                        .HasColumnType("double");

                    b.Property<double>("An")
                        .HasColumnType("double");

                    b.Property<int>("F")
                        .HasColumnType("int");

                    b.Property<int>("G")
                        .HasColumnType("int");

                    b.Property<int>("Isv")
                        .HasColumnType("int");

                    b.Property<double>("Kbpod")
                        .HasColumnType("double");

                    b.Property<double>("Kcpod")
                        .HasColumnType("double");

                    b.Property<double>("Kdpod")
                        .HasColumnType("double");

                    b.Property<double>("Kn")
                        .HasColumnType("double");

                    b.Property<double>("Kzb")
                        .HasColumnType("double");

                    b.Property<double>("Kzc")
                        .HasColumnType("double");

                    b.Property<double>("Kzd")
                        .HasColumnType("double");

                    b.Property<double>("Kzw")
                        .HasColumnType("double");

                    b.Property<int>("Mb")
                        .HasColumnType("int");

                    b.Property<double>("Pb")
                        .HasColumnType("double");

                    b.Property<double>("Pd")
                        .HasColumnType("double");

                    b.HasKey("Ks");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PrototypeApp.Model.WeldingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Arg")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("CostM")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<int>("LBH")
                        .HasColumnType("int");

                    b.Property<int>("Massa")
                        .HasColumnType("int");

                    b.Property<int>("NGN")
                        .HasColumnType("int");

                    b.Property<int>("NUN")
                        .HasColumnType("int");

                    b.Property<int>("Parg")
                        .HasColumnType("int");

                    b.Property<int>("Pmax")
                        .HasColumnType("int");

                    b.Property<string>("Specification")
                        .HasColumnType("longtext");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .HasColumnType("longtext");

                    b.Property<string>("VI")
                        .HasColumnType("longtext");

                    b.Property<string>("V_Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WeldingMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
